A=input('Enter the first matrix');
B=input('Enter the second matrix');
ans1=A+B
ans2=A-B
ans3=A*B
trans_a=A'
trans_b=B'
trans_sum=trans_a+trans_b
trans_mult=trans_a*trans_b
I=eye(3,3);
add_iden_a=A+I
add_iden_b=B+I
mult_iden_a=A*I
mult_iden_b=B*I
deter_a=det(A)
deter_b=det(B)
prod_deter=deter_a*deter_b
dia_a=diag(A)
dia_b=diag(B)
sum_dia=dia_a+dia_b